import { Theme } from './types';

export const THEMES: Theme[] = [
    {
        id: 'oferta-do-dia',
        name: 'Oferta do Dia',
        title: 'ALERTA DE OFERTAS',
        bgClass: 'bg-red-50',
        headerClass: 'bg-red-600 text-white',
        textClass: 'text-red-900',
        accentClass: 'bg-yellow-400 text-red-900',
        bannerUrl: require('../assets/banners/Ofertas-do-dia.jpeg'),
    },
    {
        id: 'fim-de-semana',
        name: 'Fim de Semana',
        title: 'ESPECIAL FIM DE SEMANA',
        bgClass: 'bg-green-50',
        headerClass: 'bg-green-700 text-white',
        textClass: 'text-green-900',
        accentClass: 'bg-yellow-400 text-green-900',
        bannerUrl: require('../assets/banners/fim_de_semana_banner.png'),
    },
    {
        id: 'hora-do-churrasco',
        name: 'Hora do Churrasco',
        title: 'HORA DO CHURRASCO',
        bgClass: 'bg-stone-100',
        headerClass: 'bg-red-900 text-white',
        textClass: 'text-stone-900',
        accentClass: 'bg-orange-500 text-white',
        bannerUrl: require('../assets/banners/Hora-do-Churrasco.jpeg'),
    },
    {
        id: 'semana-limpeza',
        name: 'Semana da Limpeza',
        title: 'SEMANA DA LIMPEZA',
        bgClass: 'bg-sky-50',
        headerClass: 'bg-sky-700 text-white',
        textClass: 'text-sky-900',
        accentClass: 'bg-yellow-400 text-sky-900',
        bannerUrl: require('../assets/banners/Semana-da-limpeza.jpeg'),
    },
    {
        id: 'fecha-mes',
        name: 'Operação Economia',
        title: 'OPERAÇÃO ECONOMIA',
        bgClass: 'bg-slate-50',
        headerClass: 'bg-slate-700 text-white',
        textClass: 'text-slate-900',
        accentClass: 'bg-yellow-400 text-slate-900',
        bannerUrl: require('../assets/banners/Operação-economia-fecha-mes.jpeg'),
    },
    {
        id: 'ofertas-semana',
        name: 'Ofertas da Semana',
        title: 'OFERTAS DA SEMANA',
        bgClass: 'bg-orange-50',
        headerClass: 'bg-orange-700 text-white',
        textClass: 'text-orange-900',
        accentClass: 'bg-red-600 text-white',
        bannerUrl: require('../assets/banners/ofertas-da-semana.jpeg'),
    },
    {
        id: 'mercearia',
        name: 'Mercearia',
        title: 'OFERTAS IMBATÍVEIS',
        bgClass: 'bg-amber-50',
        headerClass: 'bg-amber-800 text-white',
        textClass: 'text-amber-900',
        accentClass: 'bg-red-600 text-white',
        bannerUrl: require('../assets/banners/Ofertas-imbativel-de-mercearia.jpeg'),
    },
    {
        id: 'ferramentas',
        name: 'Semana das Ferramentas',
        title: 'SEMANA DAS FERRAMENTAS',
        bgClass: 'bg-zinc-100',
        headerClass: 'bg-zinc-800 text-white',
        textClass: 'text-zinc-900',
        accentClass: 'bg-yellow-400 text-zinc-900',
        bannerUrl: require('../assets/banners/semana-das-ferramentas.jpeg'),
    },
    {
        id: 'sextou',
        name: 'Sextou de Ofertas',
        title: 'SEXTOU DE OFERTAS',
        bgClass: 'bg-orange-50',
        headerClass: 'bg-red-700 text-white',
        textClass: 'text-red-900',
        accentClass: 'bg-yellow-400 text-red-900',
    },
];
